console.log(24);
console.log(typeof 24);
console.log(2.3);
console.log(typeof 2.3);
console.log(false);
console.log(typeof false);
console.log("Hola mundo!");
console.log(typeof "Hola mundo!");
console.log("c");
console.log(typeof "c");
console.log(null);
console.log(typeof null);
console.log([1,2,3]);
console.log(typeof [1,2,3]);
console.log({nombre: "Antony"});
console.log(typeof {nombre: "Antony"});
console.log(undefined);
console.log(typeof undefined);